name: Deploy react app to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy react app to GitHub Pages
        uses: ./apps/react-vite/.github/actions/deploy-to-github-pages
        with:
          app_name: react-vite
